---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
   
- name: Install packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - git

# installing node.js
- name: Add the NodeSource package signing key
  apt_key:
    url: "{{ node_key }}"
    state: present

- name: Add nodejs repo
  apt_repository:
    repo: "{{node_repo}}"
    state: present

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present

# installing forever
- name: Install forever
  npm:
    name: forever
    global: yes
    state: present

# clone git repo
- name: Clone repo
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_dest }}"
    force: yes

# installing npm packages
- name: Install local node modules
  npm:
    path: "{{ app_dest }}/js"




